services:
  web_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db_container
  db_container:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      .env
  celery_worker:
    build: .
    command: celery A- Celery_Task.celery worker --loglevel=info
    depends_on:
      - db_container
