services:
  web_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db_container
  db_container:
    image: postgres:latest
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management

    ports:
      - '15672:15672'
      - '5672:5672'



  celery_worker:
    build: .
    command: celery -A celery_task.celery worker --loglevel=info
    depends_on:
      - db_container

