"""Database

Revision ID: fb0919c942c5
Revises: 
Create Date: 2023-11-03 22:01:33.338949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0919c942c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
        sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('Category_name', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('ID'),
        sa.UniqueConstraint('Category_name')
    )
    op.create_table('order_dishes',
        sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('ID_ORDER', sa.Integer(), nullable=True),
        sa.Column('ID_DISH', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['ID_DISH'], ['dishes.ID'], ),
        sa.ForeignKeyConstraint(['ID_ORDER'], ['orders.ID'], ),
        sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('orders',
        sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('ID_USER', sa.Integer(), nullable=True),
        sa.Column('ID_ADDRESS', sa.Integer(), nullable=True),
        sa.Column('DISH', sa.Integer(), nullable=True),
        sa.Column('Status', sa.Integer(), nullable=True),
        sa.Column('Price', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['DISH'], ['order_dishes.ID_DISH'], ),
        sa.ForeignKeyConstraint(['ID_ADDRESS'], ['addresses.ID'], ),
        sa.ForeignKeyConstraint(['ID_USER'], ['users.ID'], ),
        sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('status',
        sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('Status_name', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('ID'),
        sa.UniqueConstraint('Status_name')
    )
    op.create_table('users',
        sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('User_name', sa.String(length=50), nullable=False),
        sa.Column('Password', sa.String(length=120), nullable=False),
        sa.Column('Telephone', sa.Integer(), nullable=True),
        sa.Column('Type', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('ID'),
        sa.UniqueConstraint('Password'),
        sa.UniqueConstraint('User_name')
    )
    op.create_table('addresses',
        sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('ID_USER', sa.Integer(), nullable=True),
        sa.Column('Street', sa.String(length=120), nullable=False),
        sa.Column('House', sa.String(length=50), nullable=True),
        sa.Column('Town', sa.String(length=50), nullable=True),
        sa.Column('Apt', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['ID_USER'], ['users.ID'], ),
        sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('dishes',
        sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('Dish_name', sa.String(length=50), nullable=False),
        sa.Column('Dish_price', sa.Integer(), nullable=False),
        sa.Column('Photo', sa.String(length=120), nullable=False),
        sa.Column('Category', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['Category'], ['category.Category_name'], ),
        sa.PrimaryKeyConstraint('ID'),
        sa.UniqueConstraint('Dish_name')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('status')
    op.drop_table('orders')
    op.drop_table('order_dishes')
    op.drop_table('category')
    # ### end Alembic commands ###
